import type { ParsedEndpoint, AxigenConfig } from "../types.js";
import { operationToTypeName } from "./types.js";

interface GenerateClientOptions {
  endpoints: ParsedEndpoint[];
  config: AxigenConfig;
  /** مسیر نسبی فایل types نسبت به فایل client */
  typesRelativePath?: string;
}

export function generateClientFile(opts: GenerateClientOptions): string {
  const { endpoints, config, typesRelativePath } = opts;
  const isTS = config.language !== "js";
  const instanceExport = config.axiosInstanceExport ?? "axiosInstance";

  const lines: string[] = [];

  // ─── Header ──────────────────────────────────────────────────────────────────
  lines.push(`// This file is auto-generated by axigen. DO NOT EDIT.`);
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push("");

  // ─── Imports ─────────────────────────────────────────────────────────────────
  if (isTS) {
    lines.push(`import type { AxiosResponse } from 'axios'`);
  }

  lines.push(`import { ${instanceExport} } from '${config.axiosInstancePath}'`);

  // import types
  if (isTS && typesRelativePath) {
    const typeImports = collectTypeImports(endpoints);
    if (typeImports.length > 0) {
      lines.push(`import type { ${typeImports.join(", ")} } from '${typesRelativePath}'`);
    }
  }

  lines.push("");
  lines.push("");

  // ─── Functions ───────────────────────────────────────────────────────────────
  for (const ep of endpoints) {
    const fn = buildFunction(ep, isTS, instanceExport, config.jsdoc !== false);
    lines.push(fn);
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Create a function ─────────────────────────────────────────────────────────────

function buildFunction(ep: ParsedEndpoint, isTS: boolean, instanceExport: string, jsdoc: boolean): string {
  const typeName = operationToTypeName(ep.operationId);
  const lines: string[] = [];

  // JSDoc
  if (jsdoc) {
    lines.push(`/**`);
    if (ep.summary) lines.push(` * ${ep.summary}`);
    if (ep.description && ep.description !== ep.summary) {
      lines.push(` * ${ep.description}`);
    }
    lines.push(` * \`${ep.method.toUpperCase()} ${ep.path}\``);
    if (ep.tags.length > 0) lines.push(` * @tags ${ep.tags.join(", ")}`);
    lines.push(` */`);
  }

  // signature
  const params = buildParams(ep, typeName, isTS);
  const returnType = isTS ? buildReturnType(ep, typeName) : "";
  const asyncKw = "async ";

  lines.push(`export ${asyncKw}function ${ep.operationId}(${params})${returnType} {`);

  // body
  const callLines = buildAxiosCall(ep, instanceExport, typeName, isTS);
  for (const l of callLines) {
    lines.push(`  ${l}`);
  }

  lines.push(`}`);

  return lines.join("\n");
}

// ─── Function's parameters ──────────────────────────────────────────────────────────

function buildParams(ep: ParsedEndpoint, typeName: string, isTS: boolean): string {
  const parts: string[] = [];

  // path params — required
  for (const p of ep.pathParams) {
    const type = isTS ? `: ${typeName}PathParams['${p.name}']` : "";
    parts.push(`${p.name}${type}`);
  }

  // body
  if (ep.bodySchema) {
    const optional = !ep.bodyRequired ? "?" : "";
    const type = isTS ? `: ${typeName}Body` : "";
    parts.push(`data${optional}${type}`);
  }

  // query params — if is an object
  if (ep.queryParams.length > 0) {
    const optional = ep.queryParams.every((p) => !p.required) ? "?" : "";
    const type = isTS ? `: ${typeName}QueryParams` : "";
    parts.push(`params${optional}${type}`);
  }

  return parts.join(", ");
}

// ─── return type ──────────────────────────────────────────────────────────────

function buildReturnType(ep: ParsedEndpoint, typeName: string): string {
  const responseType = ep.responseSchema ? `${typeName}Response` : "unknown";
  return `: Promise<AxiosResponse<${responseType}>>`;
}

// ─── axios call ───────────────────────────────────────────────────────────────

function buildAxiosCall(ep: ParsedEndpoint, instanceExport: string, _typeName: string, _isTS: boolean): string[] {
  const lines: string[] = [];

  // interpolate path params
  const interpolatedPath = ep.pathParams.length > 0 ? "`" + ep.path.replace(/\{(\w+)\}/g, "${$1}") + "`" : `'${ep.path}'`;

  const hasBody = !!ep.bodySchema;
  const hasQuery = ep.queryParams.length > 0;

  const method = ep.method.toLowerCase();

  if (method === "get" || method === "delete" || method === "head") {
    if (hasQuery) {
      lines.push(`return ${instanceExport}.${method}(${interpolatedPath}, { params })`);
    } else {
      lines.push(`return ${instanceExport}.${method}(${interpolatedPath})`);
    }
  } else {
    // post, put, patch
    const bodyArg = hasBody ? "data" : "undefined";
    if (hasQuery) {
      lines.push(`return ${instanceExport}.${method}(${interpolatedPath}, ${bodyArg}, { params })`);
    } else {
      lines.push(`return ${instanceExport}.${method}(${interpolatedPath}, ${bodyArg})`);
    }
  }

  return lines;
}

// ─── Collect types name for import ─────────────────────────────────────────

function collectTypeImports(endpoints: ParsedEndpoint[]): string[] {
  const names = new Set<string>();

  for (const ep of endpoints) {
    const typeName = operationToTypeName(ep.operationId);
    if (ep.pathParams.length > 0) names.add(`${typeName}PathParams`);
    if (ep.queryParams.length > 0) names.add(`${typeName}QueryParams`);
    if (ep.bodySchema) names.add(`${typeName}Body`);
    if (ep.responseSchema) names.add(`${typeName}Response`);
  }

  return [...names].sort();
}
