import type { ParsedEndpoint, AxigenConfig } from "../types.js";
import { operationToTypeName } from "./types.js";
import { resolveFunctionName } from "./function-name.js";

interface GenerateClientOptions {
  endpoints: ParsedEndpoint[];
  config: AxigenConfig;
  /** Relative path to the types file from the client file */
  typesRelativePath?: string;
}

export function generateClientFile(opts: GenerateClientOptions): string {
  const { endpoints, config, typesRelativePath } = opts;
  const isTS = config.language !== "js";
  const instanceExport = config.axiosInstanceExport ?? "axiosInstance";

  const lines: string[] = [];

  // Header
  lines.push(`// This file is auto-generated by axigen. DO NOT EDIT.`);
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push("");

  // Imports
  if (isTS) {
    lines.push(`import type { AxiosRequestConfig, AxiosResponse } from 'axios'`);
  }

  lines.push(`import { ${instanceExport} } from '${config.axiosInstancePath}'`);

  // Type imports
  if (isTS && typesRelativePath) {
    const typeImports = collectTypeImports(endpoints);
    if (typeImports.length > 0) {
      lines.push(`import type { ${typeImports.join(", ")} } from '${typesRelativePath}'`);
    }
  }

  lines.push("");
  lines.push("");

  // Functions
  for (const ep of endpoints) {
    const fn = buildFunction(ep, isTS, instanceExport, config);
    lines.push(fn);
    lines.push("");
  }

  return lines.join("\n");
}

// ─── Build a single function ──────────────────────────────────────────────────

function buildFunction(ep: ParsedEndpoint, isTS: boolean, instanceExport: string, config: AxigenConfig): string {
  const jsdoc = config.jsdoc !== false;

  // Resolve the final function name (applies transforms + appendMethod)
  const fnName = resolveFunctionName(ep.operationId, ep.method, config.functionName);
  const typeName = operationToTypeName(ep.operationId);
  const lines: string[] = [];

  // JSDoc
  if (jsdoc) {
    lines.push(`/**`);
    if (ep.summary) lines.push(` * ${ep.summary}`);
    if (ep.description && ep.description !== ep.summary) {
      lines.push(` * ${ep.description}`);
    }
    lines.push(` * \`${ep.method.toUpperCase()} ${ep.path}\``);
    if (ep.tags.length > 0) lines.push(` * @tags ${ep.tags.join(", ")}`);
    lines.push(` */`);
  }

  const params = buildParams(ep, typeName, isTS);
  const returnType = isTS ? buildReturnType(ep, typeName) : "";

  lines.push(`export async function ${fnName}(${params})${returnType} {`);

  const callLines = buildAxiosCall(ep, instanceExport);
  for (const l of callLines) {
    lines.push(`  ${l}`);
  }

  lines.push(`}`);

  return lines.join("\n");
}

// ─── Build function parameters ────────────────────────────────────────────────

function buildParams(ep: ParsedEndpoint, typeName: string, isTS: boolean): string {
  const parts: string[] = [];

  // Path params — always required
  for (const p of ep.pathParams) {
    const type = isTS ? `: ${typeName}PathParams['${p.name}']` : "";
    parts.push(`${p.name}${type}`);
  }

  // Request body
  if (ep.bodySchema) {
    const optional = !ep.bodyRequired ? "?" : "";
    const type = isTS ? `: ${typeName}Body` : "";
    parts.push(`data${optional}${type}`);
  }

  // Query params as a single object
  if (ep.queryParams.length > 0) {
    const optional = ep.queryParams.every((p) => !p.required) ? "?" : "";
    const type = isTS ? `: ${typeName}QueryParams` : "";
    parts.push(`params${optional}${type}`);
  }

  // The axios instance receives (config, options?) — both are AxiosRequestConfig
  if (isTS) {
    parts.push(`config?: AxiosRequestConfig`);
    parts.push(`options?: AxiosRequestConfig`);
  } else {
    parts.push(`config`);
    parts.push(`options`);
  }

  return parts.join(", ");
}

// ─── Build return type ────────────────────────────────────────────────────────

function buildReturnType(ep: ParsedEndpoint, typeName: string): string {
  const responseType = ep.responseSchema ? `${typeName}Response` : "unknown";
  return `: Promise<AxiosResponse<${responseType}>>`;
}

// ─── Build the axios call body ────────────────────────────────────────────────

function buildAxiosCall(ep: ParsedEndpoint, instanceExport: string): string[] {
  const lines: string[] = [];

  // Interpolate path params into a template literal if needed
  const interpolatedPath = ep.pathParams.length > 0 ? "`" + ep.path.replace(/\{(\w+)\}/g, "${$1}") + "`" : `'${ep.path}'`;

  const hasBody = !!ep.bodySchema;
  const hasQuery = ep.queryParams.length > 0;

  // Merge query params into config.params if present
  if (hasQuery) {
    lines.push(`const mergedConfig: AxiosRequestConfig = { ...config, params: { ...params, ...config?.params } }`);
  }

  const configArg = hasQuery ? "mergedConfig" : "config";

  // Build the axios call using the object form: axiosInstance({ method, url, ...config }, options)
  // This matches the custom instance signature: (config: AxiosRequestConfig, options?: AxiosRequestConfig)
  if (hasBody) {
    lines.push(
      `return ${instanceExport}(` + `{ method: '${ep.method.toUpperCase()}', url: ${interpolatedPath}, data, ...${configArg} }, ` + `options` + `)`,
    );
  } else {
    lines.push(
      `return ${instanceExport}(` + `{ method: '${ep.method.toUpperCase()}', url: ${interpolatedPath}, ...${configArg} }, ` + `options` + `)`,
    );
  }

  return lines;
}

// ─── Collect all type names needed for import ─────────────────────────────────

function collectTypeImports(endpoints: ParsedEndpoint[]): string[] {
  const names = new Set<string>();

  for (const ep of endpoints) {
    // Type names are always based on the original operationId, not the transformed fn name
    const typeName = operationToTypeName(ep.operationId);
    if (ep.pathParams.length > 0) names.add(`${typeName}PathParams`);
    if (ep.queryParams.length > 0) names.add(`${typeName}QueryParams`);
    if (ep.bodySchema) names.add(`${typeName}Body`);
    if (ep.responseSchema) names.add(`${typeName}Response`);
  }

  return [...names].sort();
}
