import type { SchemaObject, ParsedEndpoint } from "../types.js";

// ─── Schema → TypeScript type string ─────────────────────────────────────────

export function schemaToTSType(schema: SchemaObject | undefined, indent = 0): string {
  if (!schema) return "unknown";

  // $ref — extract the type name and reference it directly (no inline expansion)
  if (schema.$ref) {
    return refToTypeName(schema.$ref);
  }

  if (schema.allOf && schema.allOf.length > 0) {
    return schema.allOf.map((s) => schemaToTSType(s, indent)).join(" & ");
  }

  if (schema.anyOf || schema.oneOf) {
    const variants = (schema.anyOf ?? schema.oneOf)!;
    return variants.map((s) => schemaToTSType(s, indent)).join(" | ");
  }

  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  const nullable = schema.nullable ? " | null" : "";

  switch (schema.type) {
    case "string":
      return `string${nullable}`;
    case "number":
    case "integer":
      return `number${nullable}`;
    case "boolean":
      return `boolean${nullable}`;
    case "null":
      return "null";
    case "array":
      return `Array<${schemaToTSType(schema.items, indent)}>${nullable}`;
    case "object":
      return buildObjectType(schema, indent) + nullable;
    default:
      if (schema.properties) {
        return buildObjectType(schema, indent) + nullable;
      }
      return `unknown${nullable}`;
  }
}

function buildObjectType(schema: SchemaObject, indent: number): string {
  if (!schema.properties || Object.keys(schema.properties).length === 0) {
    return "Record<string, unknown>";
  }

  const required = new Set(schema.required ?? []);
  const pad = "  ".repeat(indent + 1);
  const closePad = "  ".repeat(indent);

  const fields = Object.entries(schema.properties)
    .map(([key, val]) => {
      const optional = !required.has(key) ? "?" : "";
      const comment = val.description ? `${pad}/** ${val.description} */\n` : "";
      const safeName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
      return `${comment}${pad}${safeName}${optional}: ${schemaToTSType(val, indent + 1)}`;
    })
    .join("\n");

  return `{\n${fields}\n${closePad}}`;
}

function refToTypeName(ref: string): string {
  // '#/components/schemas/UserResponse' → 'UserResponse'
  const parts = ref.split("/");
  return parts[parts.length - 1] ?? "unknown";
}

// ─── Generate types.ts file content ──────────────────────────────────────────

export function generateTypesFile(endpoints: ParsedEndpoint[], schemas: Record<string, SchemaObject> = {}): string {
  const lines: string[] = [];

  lines.push(`// This file is auto-generated by axigen. DO NOT EDIT.`);
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push("");

  // Track all type names declared in component schemas
  // so we skip re-declaring them in endpoint types
  const declaredInComponents = new Set<string>(Object.keys(schemas));

  // ─── Component schemas ──────────────────────────────────────────────────────
  if (Object.keys(schemas).length > 0) {
    lines.push("// ─── Component Schemas ────────────────────────────────────────────────────────");
    lines.push("");

    for (const [name, schema] of Object.entries(schemas)) {
      if (schema.description) {
        lines.push(`/** ${schema.description} */`);
      }
      lines.push(`export type ${name} = ${schemaToTSType(schema)}`);
      lines.push("");
    }
  }

  // ─── Endpoint-specific types ────────────────────────────────────────────────
  // For each endpoint we generate up to 4 types: PathParams, QueryParams, Body, Response.
  // If the schema is a $ref pointing to an already-declared component, we skip it
  // to avoid duplicate declarations.
  const endpointLines: string[] = [];

  for (const ep of endpoints) {
    const baseName = operationToTypeName(ep.operationId);

    // Path params — always inline (no $ref possible here)
    if (ep.pathParams.length > 0) {
      endpointLines.push(`export interface ${baseName}PathParams {`);
      for (const p of ep.pathParams) {
        const type = schemaToTSType(p.schema);
        const comment = p.description ? `  /** ${p.description} */\n` : "";
        endpointLines.push(`${comment}  ${p.name}: ${type}`);
      }
      endpointLines.push(`}`);
      endpointLines.push("");
    }

    // Query params — always inline
    if (ep.queryParams.length > 0) {
      endpointLines.push(`export interface ${baseName}QueryParams {`);
      for (const p of ep.queryParams) {
        const optional = !p.required ? "?" : "";
        const type = schemaToTSType(p.schema);
        const comment = p.description ? `  /** ${p.description} */\n` : "";
        endpointLines.push(`${comment}  ${p.name}${optional}: ${type}`);
      }
      endpointLines.push(`}`);
      endpointLines.push("");
    }

    // Request body
    if (ep.bodySchema) {
      const refName = getRefName(ep.bodySchema);

      if (refName && declaredInComponents.has(refName)) {
        // Already declared as a component — just re-export an alias only if the
        // endpoint type name differs from the component name
        if (`${baseName}Body` !== refName) {
          endpointLines.push(`export type ${baseName}Body = ${refName}`);
          endpointLines.push("");
        }
        // If names are identical, skip entirely — no duplicate needed
      } else {
        endpointLines.push(`export type ${baseName}Body = ${schemaToTSType(ep.bodySchema)}`);
        endpointLines.push("");
      }
    }

    // Response
    if (ep.responseSchema) {
      const refName = getRefName(ep.responseSchema);

      if (refName && declaredInComponents.has(refName)) {
        if (`${baseName}Response` !== refName) {
          endpointLines.push(`export type ${baseName}Response = ${refName}`);
          endpointLines.push("");
        }
      } else {
        endpointLines.push(`export type ${baseName}Response = ${schemaToTSType(ep.responseSchema)}`);
        endpointLines.push("");
      }
    }
  }

  if (endpointLines.length > 0) {
    lines.push("// ─── Endpoint Types ───────────────────────────────────────────────────────────");
    lines.push("");
    lines.push(...endpointLines);
  }

  return lines.join("\n");
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/** Returns the $ref component name if the schema is a direct $ref, otherwise undefined */
function getRefName(schema: SchemaObject): string | undefined {
  if (schema.$ref) return refToTypeName(schema.$ref);
  return undefined;
}

export function operationToTypeName(operationId: string): string {
  return operationId.charAt(0).toUpperCase() + operationId.slice(1);
}
