import type { SchemaObject, ParsedEndpoint } from "../types.js";

// ─── Convert schema into TypeScript type string ────────────────────────────────────

export function schemaToTSType(schema: SchemaObject | undefined, indent = 0): string {
  if (!schema) return "unknown";

  // $ref — then resolve, get name yet
  if (schema.$ref) {
    return refToTypeName(schema.$ref);
  }

  if (schema.allOf && schema.allOf.length > 0) {
    return schema.allOf.map((s) => schemaToTSType(s, indent)).join(" & ");
  }

  if (schema.anyOf || schema.oneOf) {
    const variants = (schema.anyOf ?? schema.oneOf)!;
    return variants.map((s) => schemaToTSType(s, indent)).join(" | ");
  }

  if (schema.enum) {
    return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  const nullable = schema.nullable ? " | null" : "";

  switch (schema.type) {
    case "string":
      return `string${nullable}`;
    case "number":
    case "integer":
      return `number${nullable}`;
    case "boolean":
      return `boolean${nullable}`;
    case "null":
      return "null";
    case "array":
      return `Array<${schemaToTSType(schema.items, indent)}>${nullable}`;
    case "object":
      return buildObjectType(schema, indent) + nullable;
    default:
      // Don't have type — if has properties, consider object
      if (schema.properties) {
        return buildObjectType(schema, indent) + nullable;
      }
      return `unknown${nullable}`;
  }
}

function buildObjectType(schema: SchemaObject, indent: number): string {
  if (!schema.properties || Object.keys(schema.properties).length === 0) {
    return "Record<string, unknown>";
  }

  const required = new Set(schema.required ?? []);
  const pad = "  ".repeat(indent + 1);
  const closePad = "  ".repeat(indent);

  const fields = Object.entries(schema.properties)
    .map(([key, val]) => {
      const optional = !required.has(key) ? "?" : "";
      const comment = val.description ? `${pad}/** ${val.description} */\n` : "";
      const safeName = /^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(key) ? key : `'${key}'`;
      return `${comment}${pad}${safeName}${optional}: ${schemaToTSType(val, indent + 1)}`;
    })
    .join("\n");

  return `{\n${fields}\n${closePad}}`;
}

function refToTypeName(ref: string): string {
  // #/components/schemas/UserResponse  →  UserResponse
  const parts = ref.split("/");
  return parts[parts.length - 1] ?? "unknown";
}

// ─── Generate types.ts file ────────────────────────────────────────────────────────

export function generateTypesFile(endpoints: ParsedEndpoint[], schemas: Record<string, SchemaObject> = {}): string {
  const lines: string[] = [];

  lines.push(`// This file is auto-generated by axigen. DO NOT EDIT.`);
  lines.push(`// Generated at: ${new Date().toISOString()}`);
  lines.push("");

  // ─── Component schemas ───────────────────────────────────────────────────────
  if (Object.keys(schemas).length > 0) {
    lines.push("// ─── Component Schemas ────────────────────────────────────────────────────────");
    lines.push("");

    for (const [name, schema] of Object.entries(schemas)) {
      if (schema.description) {
        lines.push(`/** ${schema.description} */`);
      }
      lines.push(`export type ${name} = ${schemaToTSType(schema)}`);
      lines.push("");
    }
  }

  // ─── Per-endpoint types ──────────────────────────────────────────────────────
  lines.push("// ─── Endpoint Types ───────────────────────────────────────────────────────────");
  lines.push("");

  for (const ep of endpoints) {
    const baseName = operationToTypeName(ep.operationId);

    // path params
    if (ep.pathParams.length > 0) {
      lines.push(`export interface ${baseName}PathParams {`);
      for (const p of ep.pathParams) {
        const type = schemaToTSType(p.schema);
        const comment = p.description ? `  /** ${p.description} */\n` : "";
        lines.push(`${comment}  ${p.name}: ${type}`);
      }
      lines.push(`}`);
      lines.push("");
    }

    // query params
    if (ep.queryParams.length > 0) {
      lines.push(`export interface ${baseName}QueryParams {`);
      for (const p of ep.queryParams) {
        const optional = !p.required ? "?" : "";
        const type = schemaToTSType(p.schema);
        const comment = p.description ? `  /** ${p.description} */\n` : "";
        lines.push(`${comment}  ${p.name}${optional}: ${type}`);
      }
      lines.push(`}`);
      lines.push("");
    }

    // request body
    if (ep.bodySchema) {
      lines.push(`export type ${baseName}Body = ${schemaToTSType(ep.bodySchema)}`);
      lines.push("");
    }

    // response
    if (ep.responseSchema) {
      lines.push(`export type ${baseName}Response = ${schemaToTSType(ep.responseSchema)}`);
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function operationToTypeName(operationId: string): string {
  return operationId.charAt(0).toUpperCase() + operationId.slice(1);
}
